[pytest]
addopts = -vvl
          --doctest-modules
doctest_optionflags =  NORMALIZE_WHITESPACE ELLIPSIS ALLOW_UNICODE ALLOW_BYTES
doctest-glob = '*.rst'
pep8maxlinelength = 160
# E402 = import not on top of the file
# E501 = ignore line length errors
# E701 = ignore multiple Line Statements - that we need for type Definitions,
# because in Classes pep is misinterpreting the type definition as multiple statement
pep8ignore = E402 E501 E701
